default_platform(:android)

platform :android do
  desc "Deploy to Google Play production track"
  lane :deploy_production do
    upload_to_play_store(
      track: "production",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON"],
      package_name: "capdesis.formulae",
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
