name: formulae
title: Formulae Pro
description: formulario sin anuncios

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  flutter_math_fork: ^0.7.4
  google_fonts: ^8.1.0
  cached_network_image: ^3.2.3
  youtube_player_flutter: ^9.0.1
  font_awesome_flutter: ^10.5.0
  share_plus: ^10.1.4
  cupertino_icons: ^1.0.5
  crypto: ^3.0.6
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_launcher_icons: 0.13.1
  universal_io: ^2.2.2
  universal_platform: ^1.0.0+1
  flutter_spinkit: ^5.2.0
  platform: ^3.1.0
  animated_text_kit: ^4.2.2
  syncfusion_flutter_pdfviewer: ^28.2.7
  http: ^1.1.0
  animated_widgets: ^1.1.0
  in_app_purchase: ^3.1.8
  flutter_animate: ^4.2.0+1
  responsive_builder: ^0.7.0
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  dio: ^5.7.0
  formulaeapps_bff_client:
    path: packages/formulaeapps_bff_client
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  emoji_picker_flutter: ^4.3.0
  image_picker: ^1.0.2
  datetime_picker_formfield: ^2.0.1
  flutter_local_notifications: ^17.2.1+2
  camera: ^0.11.0+1
  flutter_slidable: ^4.0.0
  path_provider: ^2.1.0
  pdf: ^3.10.4
  timezone: ^0.9.2
  screenshot: ^3.0.0


flutter_native_splash:
  background_image: assets/fondo_splash.png
  image: assets/icono_inicio.png



dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: any
  flutter_lints: ^4.0.0
  msix: ^3.16.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono_app_nuevo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icono_app_nuevo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icono_app_nuevo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icono_app_nuevo.png"

msix_config:
  display_name: Formulae Pro
  publisher_display_name: CAPDESIS
  store: true
  publisher: CN=5CA09431-499D-41F8-A95E-A01067B42FAF
  identity_name: CAPDESIS.FormulaePro
  msix_version: 1.1.0.0
  architectures:
    - x86
    - x64
    - arm
    - arm64
  logo_path: A:\Flutter\formulae_math_pro\assets\images\icono_app_nuevo.png
  capabilities: internetClient

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fondo_splash.png
    - assets/icono_inicio.png
    - assets/images/capdesis_logo.png
    - assets/images/chatgpt.png
    - assets/images/gif/
    - assets/images/icono_app_nuevo.png
    - assets/images/icono_app_nuevo.svg
    - assets/images/user.png

  fonts:
    - family: Sriracha
      fonts:
        - asset: fonts/Sriracha-Regular.ttf
          style: normal
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          style: normal
    - family: Noto
      fonts:
        - asset: fonts/NotoColorEmoji.ttf
          style: normal
